<?xml version="1.0" encoding="utf-8"?><Database Name="QL_XeMay" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=POLIETTA\SQLEXPRESS;Initial Catalog=QL_XeMay;Integrated Security=True" SettingsObjectName="Nhom8.Properties.Settings" SettingsPropertyName="QL_XeMayConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="IDKhachHang" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="IDKhachHang" OtherKey="IDKhachHang" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="IDTaiKhoan" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TaiKhoan" Member="TaiKhoan1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IDNhanVien" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Employee_TAIKHOAN" Member="Employee" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="IDNhanVien" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Employee_TAIKHOAN" Member="TAIKHOANs" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.Motorbikes" Member="Motorbikes">
    <Type Name="Motorbike">
      <Column Name="IDXeMay" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenXe" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Motorbike_OrderDetail" Member="OrderDetails" ThisKey="IDXeMay" OtherKey="IDXeMay" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="IDDonHang" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDXeMay" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Motorbike_OrderDetail" Member="Motorbike" ThisKey="IDXeMay" OtherKey="IDXeMay" Type="Motorbike" IsForeignKey="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="IDDonHang" OtherKey="IDDonHang" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="IDDonHang" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDKhachHang" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="IDDonHang" OtherKey="IDDonHang" Type="OrderDetail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="IDKhachHang" OtherKey="IDKhachHang" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>