//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangtamnhapkho
    {
        public int mahanghoa { get; set; }
        public int solo { get; set; }
        public Nullable<System.DateTime> nsx { get; set; }
        public Nullable<System.DateTime> hsd { get; set; }
        public Nullable<int> soluong { get; set; }
        public decimal maphieu { get; set; }
        public string tenhanghoa { get; set; }
        public int stt { get; set; }
    }
}
