//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKho_HongLamEntities : DbContext
    {
        public QuanLyKho_HongLamEntities()
            : base("name=QuanLyKho_HongLamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcongty> tblcongty { get; set; }
        public virtual DbSet<tbldangnhap> tbldangnhap { get; set; }
        public virtual DbSet<tbldvt> tbldvt { get; set; }
        public virtual DbSet<tblhanghoa> tblhanghoa { get; set; }
        public virtual DbSet<tblkiemkeCTkho> tblkiemkeCTkho { get; set; }
        public virtual DbSet<tblkiemkekho> tblkiemkekho { get; set; }
        public virtual DbSet<tblkho> tblkho { get; set; }
        public virtual DbSet<tblloaihang> tblloaihang { get; set; }
        public virtual DbSet<tbllydoxuat> tbllydoxuat { get; set; }
        public virtual DbSet<tblnhacc> tblnhacc { get; set; }
        public virtual DbSet<tblnhomhang> tblnhomhang { get; set; }
        public virtual DbSet<tblphieunhapkho> tblphieunhapkho { get; set; }
        public virtual DbSet<tblphieunhapkhoct> tblphieunhapkhoct { get; set; }
        public virtual DbSet<tblphieuxuatkho> tblphieuxuatkho { get; set; }
        public virtual DbSet<tblphieuxuatkhoct> tblphieuxuatkhoct { get; set; }
        public virtual DbSet<tbltaotem> tbltaotem { get; set; }
        public virtual DbSet<tbltonkhoct> tbltonkhoct { get; set; }
        public virtual DbSet<tbltonkhoth> tbltonkhoth { get; set; }
        public virtual DbSet<bangtamnhapkho> bangtamnhapkho { get; set; }
    }
}
