//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcongty
    {
        public tblcongty()
        {
            this.tbldangnhap = new HashSet<tbldangnhap>();
            this.tbldvt = new HashSet<tbldvt>();
            this.tblhanghoa = new HashSet<tblhanghoa>();
            this.tblkiemkekho = new HashSet<tblkiemkekho>();
            this.tblkho = new HashSet<tblkho>();
            this.tblloaihang = new HashSet<tblloaihang>();
            this.tbllydoxuat = new HashSet<tbllydoxuat>();
            this.tblnhacc = new HashSet<tblnhacc>();
            this.tblnhomhang = new HashSet<tblnhomhang>();
            this.tblphieunhapkho = new HashSet<tblphieunhapkho>();
            this.tblphieunhapkhoct = new HashSet<tblphieunhapkhoct>();
            this.tblphieuxuatkho = new HashSet<tblphieuxuatkho>();
            this.tbltaotem = new HashSet<tbltaotem>();
            this.tbltonkhoth = new HashSet<tbltonkhoth>();
            this.tbltonkhoct = new HashSet<tbltonkhoct>();
        }
    
        public int id { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string msthue { get; set; }
    
        public virtual ICollection<tbldangnhap> tbldangnhap { get; set; }
        public virtual ICollection<tbldvt> tbldvt { get; set; }
        public virtual ICollection<tblhanghoa> tblhanghoa { get; set; }
        public virtual ICollection<tblkiemkekho> tblkiemkekho { get; set; }
        public virtual ICollection<tblkho> tblkho { get; set; }
        public virtual ICollection<tblloaihang> tblloaihang { get; set; }
        public virtual ICollection<tbllydoxuat> tbllydoxuat { get; set; }
        public virtual ICollection<tblnhacc> tblnhacc { get; set; }
        public virtual ICollection<tblnhomhang> tblnhomhang { get; set; }
        public virtual ICollection<tblphieunhapkho> tblphieunhapkho { get; set; }
        public virtual ICollection<tblphieunhapkhoct> tblphieunhapkhoct { get; set; }
        public virtual ICollection<tblphieuxuatkho> tblphieuxuatkho { get; set; }
        public virtual ICollection<tbltaotem> tbltaotem { get; set; }
        public virtual ICollection<tbltonkhoth> tbltonkhoth { get; set; }
        public virtual ICollection<tbltonkhoct> tbltonkhoct { get; set; }
    }
}
