//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldangnhap
    {
        public tbldangnhap()
        {
            this.tbldvt = new HashSet<tbldvt>();
            this.tblhanghoa = new HashSet<tblhanghoa>();
            this.tblkiemkekho = new HashSet<tblkiemkekho>();
            this.tblkho = new HashSet<tblkho>();
            this.tblloaihang = new HashSet<tblloaihang>();
            this.tbllydoxuat = new HashSet<tbllydoxuat>();
            this.tblnhacc = new HashSet<tblnhacc>();
            this.tblnhomhang = new HashSet<tblnhomhang>();
            this.tblphieunhapkho = new HashSet<tblphieunhapkho>();
            this.tblphieuxuatkho = new HashSet<tblphieuxuatkho>();
            this.tbltaotem = new HashSet<tbltaotem>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public int idCongTy { get; set; }
        public int hide { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual ICollection<tbldvt> tbldvt { get; set; }
        public virtual ICollection<tblhanghoa> tblhanghoa { get; set; }
        public virtual ICollection<tblkiemkekho> tblkiemkekho { get; set; }
        public virtual ICollection<tblkho> tblkho { get; set; }
        public virtual ICollection<tblloaihang> tblloaihang { get; set; }
        public virtual ICollection<tbllydoxuat> tbllydoxuat { get; set; }
        public virtual ICollection<tblnhacc> tblnhacc { get; set; }
        public virtual ICollection<tblnhomhang> tblnhomhang { get; set; }
        public virtual ICollection<tblphieunhapkho> tblphieunhapkho { get; set; }
        public virtual ICollection<tblphieuxuatkho> tblphieuxuatkho { get; set; }
        public virtual ICollection<tbltaotem> tbltaotem { get; set; }
    }
}
