//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkho
    {
        public tblkho()
        {
            this.tblkiemkekho = new HashSet<tblkiemkekho>();
            this.tblphieunhapkho = new HashSet<tblphieunhapkho>();
            this.tblphieuxuatkho = new HashSet<tblphieuxuatkho>();
            this.tbltonkhoth = new HashSet<tbltonkhoth>();
            this.tbltonkhoct = new HashSet<tbltonkhoct>();
        }
    
        public int id { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> hide { get; set; }
        public int idcongty { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tbldangnhap tbldangnhap { get; set; }
        public virtual ICollection<tblkiemkekho> tblkiemkekho { get; set; }
        public virtual ICollection<tblphieunhapkho> tblphieunhapkho { get; set; }
        public virtual ICollection<tblphieuxuatkho> tblphieuxuatkho { get; set; }
        public virtual ICollection<tbltonkhoth> tbltonkhoth { get; set; }
        public virtual ICollection<tbltonkhoct> tbltonkhoct { get; set; }
    }
}
