//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkiemkeCTkho
    {
        public decimal id { get; set; }
        public int mahang { get; set; }
        public string solo { get; set; }
        public System.DateTime HSD { get; set; }
        public decimal sl { get; set; }
        public System.DateTime nsx { get; set; }
        public int loaihang { get; set; }
        public System.DateTime ngayud { get; set; }
        public int sttton { get; set; }
    
        public virtual tblhanghoa tblhanghoa { get; set; }
        public virtual tblloaihang tblloaihang { get; set; }
        public virtual tblkiemkekho tblkiemkekho { get; set; }
    }
}
