//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkiemkekho
    {
        public tblkiemkekho()
        {
            this.tblkiemkeCTkho = new HashSet<tblkiemkeCTkho>();
        }
    
        public decimal id { get; set; }
        public string mmyyyy { get; set; }
        public string noidung { get; set; }
        public string nguoikiemke { get; set; }
        public int idkho { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> hide { get; set; }
        public int idcongty { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tbldangnhap tbldangnhap { get; set; }
        public virtual ICollection<tblkiemkeCTkho> tblkiemkeCTkho { get; set; }
        public virtual tblkho tblkho { get; set; }
    }
}
