//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphieunhapkhoct
    {
        public decimal id { get; set; }
        public int mahanghoa { get; set; }
        public int stt { get; set; }
        public Nullable<System.DateTime> hsd { get; set; }
        public string dvt { get; set; }
        public decimal soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public int idcongty { get; set; }
        public Nullable<System.DateTime> nsx { get; set; }
        public string lot { get; set; }
        public Nullable<decimal> maphieu { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tblphieunhapkho tblphieunhapkho { get; set; }
    }
}
