//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphieuxuatkhoct
    {
        public decimal id { get; set; }
        public int mahanghoa { get; set; }
        public string tenhanghoa { get; set; }
        public int stt { get; set; }
        public int solo { get; set; }
        public Nullable<System.DateTime> hsd { get; set; }
        public string dvt { get; set; }
        public int soluong { get; set; }
        public double dongia { get; set; }
        public double thanhtien { get; set; }
    
        public virtual tblhanghoa tblhanghoa { get; set; }
    }
}
