//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphieuxuatkho
    {
        public decimal id { get; set; }
        public int ma { get; set; }
        public string nguoixuatphieu { get; set; }
        public string nguoinhanhang { get; set; }
        public string diachi { get; set; }
        public int idlydoxuat { get; set; }
        public int idkho { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> hide { get; set; }
        public int idcongty { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tbldangnhap tbldangnhap { get; set; }
        public virtual tblkho tblkho { get; set; }
        public virtual tbllydoxuat tbllydoxuat { get; set; }
    }
}
