//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphieunhapkho
    {
        public tblphieunhapkho()
        {
            this.tblphieunhapkhoct = new HashSet<tblphieunhapkhoct>();
        }
    
        public decimal id { get; set; }
        public int ma { get; set; }
        public string nguoinhapphieu { get; set; }
        public string nguoigiaohang { get; set; }
        public string diachi { get; set; }
        public string masothue { get; set; }
        public string diengiai { get; set; }
        public int idkho { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> hide { get; set; }
        public int idcongty { get; set; }
        public System.DateTime ngayud { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tbldangnhap tbldangnhap { get; set; }
        public virtual tblkho tblkho { get; set; }
        public virtual ICollection<tblphieunhapkhoct> tblphieunhapkhoct { get; set; }
    }
}
