//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltonkhoct
    {
        public decimal id { get; set; }
        public int idkho { get; set; }
        public Nullable<decimal> idn { get; set; }
        public Nullable<decimal> idx { get; set; }
        public int mahanghoa { get; set; }
        public int solo { get; set; }
        public Nullable<System.DateTime> hsd { get; set; }
        public Nullable<decimal> tondau { get; set; }
        public Nullable<decimal> sln { get; set; }
        public Nullable<decimal> slx { get; set; }
        public Nullable<System.DateTime> ngayud { get; set; }
        public int idcongty { get; set; }
        public Nullable<decimal> idnguoikk { get; set; }
    
        public virtual tblcongty tblcongty { get; set; }
        public virtual tblkho tblkho { get; set; }
    }
}
