# Generated by Django 5.0.4 on 2024-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuiSach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_address',
            new_name='customer_user',
        ),
    ]
