# Generated by Django 5.0.4 on 2024-05-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TuiSach", "0002_rename_customer_address_customers_customer_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "ma_chi_tiet_don_hang",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("so_luong", models.IntegerField()),
                ("gia_don_vi", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "chitietdonhang",
            },
        ),
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                ("ma_danh_muc", models.AutoField(primary_key=True, serialize=False)),
                ("ten_danh_muc", models.CharField(max_length=255)),
                ("mo_ta", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "danhmuc",
            },
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                ("ma_don_hang", models.AutoField(primary_key=True, serialize=False)),
                ("ngay_dat_hang", models.DateTimeField()),
                ("tong_tien", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "donhang",
            },
        ),
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                ("ma_khach_hang", models.AutoField(primary_key=True, serialize=False)),
                ("ho_ten", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("dia_chi", models.CharField(blank=True, max_length=255, null=True)),
                ("gioi_tinh", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "khachhang",
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                ("ma_san_pham", models.AutoField(primary_key=True, serialize=False)),
                ("ten_san_pham", models.CharField(max_length=255)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("gia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("so_luong", models.IntegerField()),
                (
                    "hinh_anh_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ma_danh_muc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TuiSach.danhmuc",
                    ),
                ),
            ],
            options={
                "db_table": "sanpham",
            },
        ),
        migrations.CreateModel(
            name="TaiKhoan",
            fields=[
                ("ma_tai_khoan", models.AutoField(primary_key=True, serialize=False)),
                ("ten_tai_khoan", models.CharField(max_length=255, unique=True)),
                ("mat_khau", models.CharField(max_length=255)),
                ("chuc_vu", models.IntegerField()),
            ],
            options={
                "db_table": "taikhoan",
            },
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.AddField(
            model_name="chitietdonhang",
            name="ma_don_hang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TuiSach.donhang"
            ),
        ),
        migrations.AddField(
            model_name="donhang",
            name="ma_khach_hang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TuiSach.khachhang"
            ),
        ),
        migrations.AddField(
            model_name="chitietdonhang",
            name="ma_san_pham",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TuiSach.sanpham"
            ),
        ),
    ]
