# Generated by Django 5.0.4 on 2024-05-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuiSach', '0003_chitietdonhang_danhmuc_donhang_khachhang_sanpham_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taikhoan',
            old_name='ma_tai_khoan',
            new_name='ma_khach_hang',
        ),
    ]
