# Generated by Django 5.0.4 on 2024-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TuiSach", "0004_rename_ma_tai_khoan_taikhoan_ma_khach_hang"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanpham",
            name="hinh_anh_url",
        ),
        migrations.AddField(
            model_name="sanpham",
            name="hinh_anh",
            field=models.ImageField(blank=True, null=True, upload_to="DO AN/Images/"),
        ),
    ]
